Problem solved. Need to ensure integration tests do not use the springboot uber jar.
See https://stackoverflow.com/questions/50787704/maven-failsafe-fails-with-java-lang-noclassdeffounderror/59993262

Also upgrated java and springboot versions